# Generated by Django 4.1 on 2022-09-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
