# Generated by Django 4.1 on 2022-09-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_account_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='aadhar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='pan',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
