# Generated by Django 4.1 on 2022-10-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_account_aadhar_account_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
