# Generated by Django 4.1 on 2022-10-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_alter_account_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Year',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='day',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='month',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
