# Generated by Django 4.1 on 2022-10-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_account_year_account_day_account_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Year',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='day',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='month',
            field=models.CharField(max_length=255),
        ),
    ]
