# Generated by Django 4.1 on 2022-10-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_alter_account_year_alter_account_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='prefix',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
