# Generated by Django 4.1b1 on 2023-10-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0010_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='null', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='uname',
            field=models.CharField(default='null', max_length=100, unique=True),
        ),
    ]
