# Generated by Django 4.1b1 on 2023-10-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0012_alter_user_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uname',
            new_name='username',
        ),
    ]
